global:
  config_version: 3
input:
  type: file
  path: /home/ubuntu/Py3Docker/record.log
  readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
imports:
- type: grok_patterns
  dir: ./patterns
grok_patterns:
- 'EXIM_MESSAGE [a-zA-Z ]*'
metrics:
- type: counter
  name: python3_flask_http
  help: Total number of http requests on website.
  match: '%{DATE} %{TIME} , %{WORD:lognamenum}:%{INT} , %{WORD:modulename} , %{GREEDYDATA:message}'
  labels:
    lognamenuum: '{{.lognamenum}}'
    module: '{{.modulename}}'
    message: '{{.message}}'
server:
  protocol: http
  port: 9144
